services:
  web:
    image: snegzok/my-app:latest
    # Мы УДАЛИЛИ строку ports: "81:8080", теперь за это отвечает Traefik
    networks:
      - web  # Та самая сеть, которая была в конфиге Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`app.expert-only.ru`)"
      # МЕНЯЕМ ТОЧКУ ВХОДА НА ЗАЩИЩЕННУЮ:
      - "traefik.http.routers.myapp.entrypoints=websecure"
      # ВКЛЮЧАЕМ SSL (используем резолвер из конфига Traefik):
      - "traefik.http.routers.myapp.tls.certresolver=myresolver"
      - "traefik.http.services.myapp.loadbalancer.server.port=8080"

networks:
  web:
    external: true
