name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # ЭТАП 1: Сборка и отправка в Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:v1.0.0

  # ЭТАП 2: Команда на запуск через Compose на виртуалке
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Ждем, пока билд закончится
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/proect-github
            # Заставляем Compose скачать новый образ из Hub и перезапустить контейнер
            docker compose pull
            docker compose up -d
